### ISSUE TITLE
About permission when run

### ISSUE THREAD

**Issue by havudk1707** [ikiapps/Setup-Xcode-Derived-Data-RAM-Disk#1]
Can you explain about this sentence.
"The minimum permission for this property list launch agent file is that it is readable by you."
I run in terminal:
`launchctl load com.ikiapps.setupXcodeDerivedDataRamDisk.plist`
And this is error: Path had bad ownership/permissions
I tried run this command:
sudo chown root com.ikiapps.setupXcodeDerivedDataRamDisk.plist 
sudo chgrp wheel com.ikiapps.setupXcodeDerivedDataRamDisk.plist 
But have a same error like that.
Thank you very much

**Comment by d108** [comment]
Sure. "Readable by you" means readable by _your user account._

Since the launch agent exists in your user folder you don’t want to have root ownership set on it. Instead, you want the file to have permissions that correspond to **your user account.**  If you change that, it should eliminate the error you are receiving.
